In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector1 = tf.constant([2,3])
vector2 = tf.constant((2,3))
vector1 , vector2

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [ ]:
MATRIX1 = tf.constant([[2,3]])
MATRIX2 = tf.constant((1,2,3))
MATRIX1 , MATRIX2

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

In [ ]:
TENSOR1 = tf.constant(
    [
      [
      [2,3]
      ]
    ]
  )

TENSOR1

<tf.Tensor: shape=(1, 1, 2), dtype=int32, numpy=array([[[2, 3]]], dtype=int32)>

In [ ]:
scalar.ndim , vector1.ndim , MATRIX1.ndim , TENSOR1.ndim

(0, 1, 2, 3)

#creating tensors with `tf.Variable`


In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# changeable_tensor[0] = 7 we cannot directly change  values in tensors

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# unchangeable_tensor[0].assign(7)  cannot change unchangeable tensors i.e tensor created with constant.......
# unchangeable_tensor

#creating random tensor

In [ ]:
random_1  = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
shuffled = tf.random.shuffle(not_shuffled) #shuffles along 1st dimension her iy is 3....we can also put seed in it
# shuffled  = tf.random.shuffle(not_shuffled , seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# tf.random.set_seed(42) # global level random seed
# shuffled  = tf.random.shuffle(not_shuffled , seed=42) operation level random seed.....

# other ways to make tensors

In [ ]:
ones  = tf.ones([2,3])
ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
zeros = tf.zeros([2,3])
zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#turn numpy arrays into tensors

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)

tensor_A = tf.constant(numpy_A)
tensor_B = tf.constant(numpy_A , shape=(2,3,4)) # 2*3*4 = 24 , which is equal to elements of numpy_A......
numpy_A,tensor_A,tensor_B

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

## Geting info from tensors

* Shape  like its the length of all dimension of the tensor
* Rank  tensor.ndim
* Axis or Dimension  tensor[0] , tensor[:,1]
* Size  no. of elements in the tensor

# Indexing tensors

In [ ]:
#tensor can be indexed like python list

some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
tensor  = tf.random.Generator.from_seed(42)
tensor = tensor.normal(shape=(2,3,4))
tensor

tensor , tensor[: , 0] # 0th from each one


(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
         [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
         [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
         [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
         [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],
       dtype=float32)>)

In [ ]:
 tensor[0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.7565803>

In [ ]:
#to add a axis in tensor

tensor_new = tensor[...,tf.newaxis] # we can add a new axis anywhere
tensor_new , tensor_new.shape

(<tf.Tensor: shape=(2, 3, 4, 1), dtype=float32, numpy=
 array([[[[-0.7565803 ],
          [-0.06854702],
          [ 0.07595026],
          [-1.2573844 ]],
 
         [[-0.23193763],
          [-1.8107855 ],
          [ 0.09988727],
          [-0.50998646]],
 
         [[-0.7535805 ],
          [-0.57166284],
          [ 0.1480774 ],
          [-0.23362993]]],
 
 
        [[[-0.3522796 ],
          [ 0.40621263],
          [-1.0523509 ],
          [ 1.2054597 ]],
 
         [[ 1.6874489 ],
          [-0.4462975 ],
          [-2.3410842 ],
          [ 0.99009085]],
 
         [[-0.0876323 ],
          [-0.635568  ],
          [-0.6161736 ],
          [-1.9441465 ]]]], dtype=float32)>,
 TensorShape([2, 3, 4, 1]))

In [ ]:
#aternative to tf.newaxis

tf.expand_dims(tensor , axis=-1) # -1 means expand the final axis , 0 means expand the 0th axis i.e front

<tf.Tensor: shape=(2, 3, 4, 1), dtype=float32, numpy=
array([[[[-0.7565803 ],
         [-0.06854702],
         [ 0.07595026],
         [-1.2573844 ]],

        [[-0.23193763],
         [-1.8107855 ],
         [ 0.09988727],
         [-0.50998646]],

        [[-0.7535805 ],
         [-0.57166284],
         [ 0.1480774 ],
         [-0.23362993]]],


       [[[-0.3522796 ],
         [ 0.40621263],
         [-1.0523509 ],
         [ 1.2054597 ]],

        [[ 1.6874489 ],
         [-0.4462975 ],
         [-2.3410842 ],
         [ 0.99009085]],

        [[-0.0876323 ],
         [-0.635568  ],
         [-0.6161736 ],
         [-1.9441465 ]]]], dtype=float32)>

In [ ]:
tensor , tf.expand_dims(tensor , axis=0) # expand the first axis

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
         [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
         [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
         [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
         [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
 array([[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
          [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
          [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
 
         [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
          [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
          [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]]],
       dtype=float32)>)

# manupulating tensors ( tensor operations )

+ , - , / , *

In [ ]:
ex = np.arange(1,10,1)
ex , ex+10 , ex-10 , ex*10 ,ex/10

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([-9, -8, -7, -6, -5, -4, -3, -2, -1]),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]),
 array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [ ]:
#we can also use tenor built in functions

# matrix multiplication

In [ ]:
ex2 = tf.random.Generator.from_seed(42)
ex2 = ex2.normal(shape=(10,1))

ex = tf.random.Generator.from_seed(42)
ex = ex.normal(shape=(1,10))
# or we can use reshape....tf.reshape(ex , shape=(1,10))

#or we can use transpose.....tf.transpose(ex)
tf.matmul(ex,ex2)

#tf.matmul(ex,tf.reshape(ex , shape=(10,1)))
#tf.matmul(ex,tf.transpose(ex))


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.6613812]], dtype=float32)>

#the dot product

In [ ]:
tf.tensordot(ex,ex2,axes=1)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.6613812]], dtype=float32)>

#type conversion

In [ ]:
B = tf.constant([1.7,7.4])
D = tf.cast(B ,  dtype=tf.float16)
D , B

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

# Agregating tensors

means condensing them from multiple values to smaller amount of values

In [ ]:
#get absolute values

ex = tf.constant([-7,-10])
tf.abs(ex)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# so we can use

ex = tf.constant(np.random.randint(0,100,size=50))
tf.reduce_min(ex) , tf.reduce_max(ex) , tf.reduce_mean(ex) , tf.reduce_sum(ex)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=48>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2442>)

#squeezing a tensor ( removing all single dimesions )

In [ ]:
#crate a tensor to get started

G = tf.constant(tf.random.uniform(shape=[40]),shape=(1,1,1,1,40))
#G = tf.constant(tf.random.uniform(shape=(1,1,1,1,40)))
G

<tf.Tensor: shape=(1, 1, 1, 1, 40), dtype=float32, numpy=
array([[[[[0.12282109, 0.87659025, 0.8391094 , 0.28007746, 0.24168587,
           0.3053664 , 0.3159418 , 0.852672  , 0.6352539 , 0.65264046,
           0.24034572, 0.15530908, 0.99263096, 0.3985201 , 0.8946359 ,
           0.43693566, 0.99105597, 0.8900813 , 0.34673226, 0.70551693,
           0.9053731 , 0.34162915, 0.49820566, 0.54331744, 0.36127305,
           0.24839914, 0.5099844 , 0.7339568 , 0.13222373, 0.41661584,
           0.9712976 , 0.8984407 , 0.54634845, 0.60200953, 0.27083123,
           0.8101857 , 0.44028676, 0.6665337 , 0.32965755, 0.01366806]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(40,), dtype=float32, numpy=
 array([0.12282109, 0.87659025, 0.8391094 , 0.28007746, 0.24168587,
        0.3053664 , 0.3159418 , 0.852672  , 0.6352539 , 0.65264046,
        0.24034572, 0.15530908, 0.99263096, 0.3985201 , 0.8946359 ,
        0.43693566, 0.99105597, 0.8900813 , 0.34673226, 0.70551693,
        0.9053731 , 0.34162915, 0.49820566, 0.54331744, 0.36127305,
        0.24839914, 0.5099844 , 0.7339568 , 0.13222373, 0.41661584,
        0.9712976 , 0.8984407 , 0.54634845, 0.60200953, 0.27083123,
        0.8101857 , 0.44028676, 0.6665337 , 0.32965755, 0.01366806],
       dtype=float32)>,
 TensorShape([40]))

#One-hot encoding

In [ ]:
some_list  = [0,1,2,4]
tf.one_hot(some_list , depth=4) # on_value = 1 , off_value = 0
#it does on_value to 0th index of 0th array, 1st to 1st and 4th to 4th array....
#we can also change the on and off value


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list , depth=5 , on_value="hello" , off_value="world")
#dept is used to tell number of array in (1, depth) shape

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'hello', b'world', b'world', b'world', b'world'],
       [b'world', b'hello', b'world', b'world', b'world'],
       [b'world', b'world', b'hello', b'world', b'world'],
       [b'world', b'world', b'world', b'world', b'hello']], dtype=object)>

In [ ]:

tf.math.log(tf.cast(tf.range(1,10) , dtype=tf.float32)) , tf.sqrt(tf.cast(tf.range(1,10) , dtype=tf.float32))  #sqrt and log requires non int type of value

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>)

if we want to calculate a price of a house and we have 3 inputs like no of room , bathroom and cars ......i.e 3 inputs.....so we need to wrap these 3 inputs in an [ ]
which will increase the shape (1,3) so we need to remove 1 dimension ( outside one) to get a single dimension output.....

the actual shape oif input is 3 but the feeding shape is 1,3 and the output shape is 1 or depend on type of output......


In [ ]:
[[0,0,0,1], # means 3 room
 [0,0,0,1], #4 bathroom
 [0,0,1,0] # 3 cars
 ]

[[0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 1, 0]]